<Program> ::= <Expression> "," <Program> | <Expression>;
<Expression> ::= <Addition>;
<Addition> ::=
    <Multiplication> <AdditionPrime>
;
<AdditionPrime> ::=
    "+" <Multiplication> <AdditionPrime> |
    "-" <Multiplication> <AdditionPrime> |
    <Empty>
;
<Multiplication> ::=
    <Negation> <MultiplicationPrime>
;
<MultiplicationPrime> ::=
    "*" <Negation> <MultiplicationPrime> |
    "/" <Negation> <MultiplicationPrime> |
    <Empty>
;
<Negation> ::=
    "-" <Expression> |
    <Primary>
;
<Primary> ::=
    "(" <Expression> ")" |
    <Number>
;
<Number> ::= [0-9]+;