<Expression> ::= <Addition> | <Multiplication> | <Negation> | "(" <Expression> ")" | <Number>;
<Addition> ::= <Expression> ("+" | "-") <Expression>;
<Multiplication> ::= <Expression> ("*" | "/") <Expression>;
<Negation> ::= "-" <Expression>;


<Expression> ::= <Addition>;
<Addition> ::= 
    <Expression> "+" <Multiplication> |
    <Expression> "-" <Multiplication> |
    <Multiplication>
;
<Multiplication> ::=
    <Expression> "*" <Multiplication> |
    <Expression> "/" <Multiplication> |
    <Negation>
;
<Negation> ::=
    "-" <Expression> |
    <Primary>
;
<Primary> ::=
    "(" <Expression> ")" |
    <Number>
;