<Program> ::= <Expression> "," <Program> | <Expression> "EOF";
<Expression> ::= <Addition>;
<Addition> ::=
    <Multiplication> <AdditionPrime>
;
<AdditionPrime> ::=
    "+" <Multiplication> <AdditionPrime> |
    "-" <Multiplication> <AdditionPrime> |
    <Empty>
;
<Multiplication> ::=
    <Power> <MultiplicationPrime>
;
<MultiplicationPrime> ::=
    "*" <Power> <MultiplicationPrime> |
    "/" <Power> <MultiplicationPrime> |
    <Empty>
;
<Power> ::=
    <Negation> <PowerPrime>
;
<PowerPrime> ::=
    "**" <Negation> <PowerPrime> |
    <Empty>
;
<Negation> ::=
    "-" <Expression> |
    <Primary>
;
<Primary> ::=
    "(" <Expression> ")" |
    <Number>
;
<Number> ::= [0-9]+;