GlobalUsingsConfig:
  namespace: ""
  usings: ""
  generator: GlobalUsings.py
  dst: "NUL:"
  display name: "Generate-Global-Usings"

  data:
    aliases:
      BackingNumberType: byte
      HighLevelOpcodeBackingType: uint
      SmallFunctionSignature: Common.Metadata.FunctionSignature<byte, SmallLang.IR.Metadata.SmallLangType>
      SmallFunctionID: Common.Metadata.FunctionID<byte>
    usings: {}

