TypeData:
  namespace: SmallLang.IR.Metadata
  usings: [SmallLang.Exceptions]
  generator: typedata.py
  dst: IR/Metadata/Generated/TypeData.cs
  display name: "Generate-TypeData"

  name: TypeData
  data:
    typecodes:
      &void void: 0
      &string string: 1
      &float float: 2
      &int int: 3
      &double double: 4
      &number number: 5
      &long long: 6
      &longint longint: 7
      &byte byte: 8
      &char char: 9
      &bool bool: 10
      &rational rational: 11
      &array array: 12
      &list list: 13
      &set set: 14
      &dict dict: 15

    type info:
      - name: *void
        size: 0
        is pointer: no
        is number: no
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: null
      - name: *string
        size: 4
        is pointer: yes
        is number: no
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: null
      - name: *float
        size: 4
        is pointer: no
        is number: yes
        is collection: no
        simulates real number: yes
        simulates rational number: no
        value max size: 32
      - name: *int
        size: 4
        is pointer: no
        is number: yes
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: 32
      - name: *double
        size: 8
        is pointer: no
        is number: yes
        is collection: no
        simulates real number: yes
        simulates rational number: no
        value max size: 64
      - name: *number
        size: 4
        is pointer: yes
        is number: yes
        is collection: no
        simulates real number: yes
        simulates rational number: no
        value max size: null
      - name: *long
        size: 8
        is pointer: no
        is number: yes
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: 64
      - name: *longint
        size: 4
        is pointer: yes
        is number: yes
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: null
      - name: *byte
        size: 1
        is pointer: no
        is number: yes
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: 8
      - name: *char
        size: 1
        is pointer: no
        is number: yes
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: 8
      - name: *bool
        size: 1
        is pointer: no
        is number: yes
        is collection: no
        simulates real number: no
        simulates rational number: no
        value max size: 1
      - name: *rational
        size: 4
        is pointer: yes
        is number: yes
        is collection: no
        simulates real number: no
        simulates rational number: yes
        value max size: null
      - name: *array
        size: 4
        is pointer: yes
        is number: no
        is collection: yes
        simulates real number: no
        simulates rational number: no
        value max size: null
      - name: *list
        size: 4
        is pointer: yes
        is number: no
        is collection: yes
        simulates real number: no
        simulates rational number: no
        value max size: null
      - name: *set
        size: 4
        is pointer: yes
        is number: no
        is collection: yes
        simulates real number: no
        simulates rational number: no
        value max size: null
      - name: *dict
        size: 4
        is pointer: yes
        is number: no
        is collection: yes
        simulates real number: no
        simulates rational number: no
        value max size: null
    
    implicit casts:
      *string : []
      *longint : [*rational, *number]
      *rational : [*number]
      *array : []
      *list : [*array]
      *set : []
      *dict : []
      

    pointer types:
      - *string
      - *number
      - *longint
      - *rational
      - *array
      - *list
      - *set
      - *dict


Functions:
  
  namespace: SmallLang.IR.Metadata
  usings: [Common.Metadata]
  generator: functions.py
  dst: IR/Metadata/Generated/Functions__StdLibFunctions.cs
  display name: "Generate-Stdlib-Functions"

  name: Functions

  data:
    - {name: Input, ID: 1, returns: string, arguments: []}
    - {name: SOut, ID: 2, returns: void, arguments: [string]}
    - {name: GetLength, ID: 3, returns: int, arguments: [list]}
    - {name: ConstructList, ID: 4, returns: list, arguments: [void]}
    - {name: ConstructArray, ID: 5, returns: array, arguments: [void]}
    # - {name: ConstructCollection, ID: 6, returns: collection, arguments: [void]}
    - {name: ConstructSet, ID: 7, returns: set, arguments: [void]}
    - {name: ConstructDict, ID: 8, returns: dict, arguments: [void]}
    - {name: __CastTo__float, ID: 9, returns: float, arguments: [void]} #args: stack: {TOP}[type of src, src]{BOTTOM}
    - {name: __CastTo__int, ID: 10, returns: int, arguments: [void]}
    - {name: __CastTo__double, ID: 11, returns: double, arguments: [void]}
    - {name: __CastTo__number, ID: 12, returns: number, arguments: [void]}
    - {name: __CastTo__long, ID: 13, returns: long, arguments: [void]}
    - {name: __CastTo__longint, ID: 14, returns: longint, arguments: [void]}
    - {name: __CastTo__byte, ID: 15, returns: byte, arguments: [void]}
    - {name: __CastTo__char, ID: 16, returns: char, arguments: [void]}
    - {name: __CastTo__bool, ID: 17, returns: bool, arguments: [void]}
    - {name: __CastTo__rational, ID: 18, returns: rational, arguments: [void]}
    - {name: __CastTo__array, ID: 19, returns: array, arguments: [void]}
    - {name: __CastTo__list, ID: 20, returns: list, arguments: [void]}
    - {name: __CastTo__set, ID: 21, returns: set, arguments: [void]}
    - {name: __CastTo__dict, ID: 22, returns: dict, arguments: [void]}