Section: Statement*
Statement: [SCExpr | Loop | Cond | Function | Block | ReturnStatement | LoopControlStatement]
SCExpr: Expression Semicolon [d]
ReturnStatement: Return [d] Expression Semicolon [d]
LoopControlStatement: [Break | Continue] NestedValueInLoopControl? Semicolon [d]
NestedValueInLoopControl: Identifier
Loop: ForLoopHeader LoopLabel? Statement Else?
Loop: WhileLoopHeader LoopLabel? Statement Else?
LoopLabel: As [d] Identifier
ForLoopHeader: For [d] OpenParen [d] Expression Semicolon [d] Expression Semicolon [d] Expression CloseParen [d]
WhileLoopHeader: While [d] OpenParen [d] Expression CloseParen [d]
Cond: [Switch | If]
If: If [d] OpenParen [d] Expression CloseParen [d] Statement Else?
Else: Else [d] Statement
Switch: Switch [d] OpenParen [d] Expression CloseParen [d] OpenCurly [d] SwitchBody* CloseCurly [d]
SwitchBody: Expression Colon [d] Statement
Function: Type Identifier OpenParen [d] TypeAndIdentifierCSV? CloseParen [d] Statement
TypeAndIdentifierCSV: TypeAndIdentifierCSVElement (Comma [d] TypeAndIdentifierCSV)*
TypeAndIdentifierCSVElement: FunctionArgDeclModifiersCombined? Type Identifier
Block: OpenCurly [d] Section CloseCurly [d]
Expression: AliasExpr
AliasExpr: [AliasExpr1 | AliasExpr2 | AliasExpr3 | DeclarationExpr]
AliasExpr1: Identifier As [d] Identifier
AliasExpr2: Identifier As [d] Type Identifier
AliasExpr3: Identifier As [d] Type
DeclarationExpr: [DeclarationExpr1 | AssignmentExpr]
DeclarationExpr1: DeclarationModifiersCombined? Type Identifier AssignmentPrime?
DeclarationModifiersCombined: DeclarationModifier+
DeclarationModifier: [Ref | Readonly | Frozen | Immut]
FunctionArgDeclModifier: [Ref | Readonly | Frozen | Immut | Copy]
FunctionArgDeclModifiersCombined: FunctionArgDeclModifier+
AssignmentPrime: Equals Expression
AssignmentExpr: AssignmentExpr1
AssignmentExpr1: SmallLangParser_expressions
Primary: LPrimary PrimaryPrime?
PrimaryPrime: IndexPrime
PrimaryPrime:  FunctionCallPrime
IndexPrime: OpenSquare [d] Expression CloseSquare [d]
LPrimary: [NewExpr | LPrimary1 | LPrimary2 | LPrimary3]
LPrimary1: OpenParen [d] Expression CloseParen [d]
LPrimary2: Copy [d] Expression
LPrimary3: [Identifier | Number | String | TrueLiteral | FalseLiteral]
NewExpr: New [d] Type OpenParen [d] ArgList? CloseParen [d]
FunctionCallPrime:OpenParen [d] ArgList? CloseParen [d]
ArgList: ArgListElement ArgListPrime*
ArgListElement: ArgumentLabel? Expression
ArgListPrime: Comma [d] ArgListElement
ArgumentLabel: Identifier Colon [d]
TypeCSV: Type (Comma [d] Type)*
Type: [BaseType | GenericType]
GenericType: [TypeArray | TypeList | TypeSet | TypeDict | TypeCollection] OpenAngleSquare [d] TypeCSV CloseAngleSquare [d]
BaseType: [TypeByte | TypeShort | TypeInt | TypeLong | TypeLongInt | TypeFloat | TypeDouble | TypeRational | TypeNumber | TypeString | TypeChar | TypeVoid]


Expression EqualTo Expression - Right Associative
Expression NotEqualTo Expression - Right Associative
Expression GreaterThan Expression - Right Associative
Expression LessThan Expression - Right Associative
Expression GreaterThanOrEqualTo Expression - Right Associative
Expression LessThanOrEqualTo Expression - Right Associative
LogicalNot Expression - Right Associative
BitwiseNegation Expression - Right Associative
Subtraction Expression - Right Associative
Expression Equals Expression - Right Associative
Expression LogicalOr Expression - Left Associative
Expression LogicalXor Expression - Left Associative
Expression LogicalAnd Expression - Left Associative
Expression Addition Expression - Left Associative
Expression Subtraction Expression - Left Associative
Expression Division Expression - Left Associative
Expression Multiplication Expression - Left Associative
Expression Exponentiation Expression - Right Associative
Expression Subtraction Expression - Left Associative
Expression BitwiseOr Expression - Left Associative
Expression BitwiseXor Expression - Left Associative
Expression BitwiseAnd Expression - Left Associative
Expression BitwiseLeftShift Expression - Left Associative
Expression BitwiseRightShift Expression - Left Associative
Expression PlusEquals Expression - Right Associative
Expression MinusEquals Expression - Right Associative
Expression MultiplicationEquals Expression - Right Associative
Expression DivideEquals Expression - Right Associative
Expression PowerEquals Expression - Right Associative
Expression BitwiseAndEquals Expression - Right Associative
Expression BitwiseOrEquals Expression - Right Associative
Expression BitwiseXorEquals Expression - Right Associative
Expression BitwiseNegateEquals Expression - Right Associative
Expression LeftShiftEquals Expression - Right Associative
Expression RightShiftEquals Expression - Right Associative
Increment Expression - Left Associative
Decrement Expression - Right Associative